#!/usr/bin/env bash
# A script that sets up and configures HAproxy on your lb-01 server

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install haproxy

echo "

frontend macmilliansolutions
    bind *:80
    mode http
    default_backend macmilliansolutions

backend macmilliansolutions
    mode http
    balance roundrobin
    server 464372-web-01 34.204.76.2:80 check
    server 464372-web-02 34.207.211.35:80 check
" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart
