#!/bin/bash

function ping_ip() {
    # Check if an argument was passed
    if [ -z "$1" ]; then
        echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
        return 1
    fi

    # Ping the IP address 5 times
    ping -c 5 $1
}

ping_ip $1

